# Generated by Django 4.1.6 on 2023-06-22 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_livro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='cover_image_url',
            field=models.ImageField(upload_to='livros/'),
        ),
    ]
