# Generated by Django 4.1.6 on 2023-06-22 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_livro_cover_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('custo', models.IntegerField()),
                ('vida', models.IntegerField()),
                ('mana', models.IntegerField()),
                ('armadura', models.IntegerField()),
                ('ap', models.IntegerField()),
                ('dps', models.IntegerField()),
                ('dano', models.IntegerField()),
                ('crti_rate', models.IntegerField()),
                ('alcance', models.IntegerField()),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build', to='api.build')),
            ],
        ),
        migrations.CreateModel(
            name='Champion_Habilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('ativo', models.BooleanField(default=False)),
                ('descricao', models.TextField()),
                ('dano', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('bonus', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Item_Basico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('buff', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Item_Completo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('buff', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Item_Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item1', to='api.item_basico')),
                ('item2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item2', to='api.item_basico')),
            ],
        ),
        migrations.CreateModel(
            name='Melhoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('bonus', models.TextField()),
                ('tier', models.CharField(choices=[('Prata', 'Prata'), ('Ouro', 'Ouro'), ('Prismatico', 'Prismático')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Origem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('bonus', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Livro',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.AddField(
            model_name='item_completo',
            name='receita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_completo', to='api.item_receita'),
        ),
        migrations.AddField(
            model_name='champion',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classe', to='api.classe'),
        ),
        migrations.AddField(
            model_name='champion',
            name='habilidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilidade', to='api.champion_habilidade'),
        ),
        migrations.AddField(
            model_name='champion',
            name='origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origem', to='api.origem'),
        ),
        migrations.AddField(
            model_name='build',
            name='item1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item1', to='api.item_completo'),
        ),
        migrations.AddField(
            model_name='build',
            name='item2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item2', to='api.item_completo'),
        ),
        migrations.AddField(
            model_name='build',
            name='item3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item3', to='api.item_completo'),
        ),
    ]
