# Generated by Django 4.1.6 on 2023-06-23 07:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_build_champion_champion_habilidade_classe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_receita',
            name='nome',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='champion',
            name='habilidade',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Champion_Habilidade',
        ),
    ]
