# Generated by Django 4.1.6 on 2023-06-23 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_item_receita_nome_alter_champion_habilidade_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='champion',
            old_name='crti_rate',
            new_name='crit_rate',
        ),
    ]
