# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import champion_pb2 as champion__pb2


class ChampionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetChampionByName = channel.unary_unary(
                '/ChampionService/GetChampionByName',
                request_serializer=champion__pb2.ChampionNameRequest.SerializeToString,
                response_deserializer=champion__pb2.Champion.FromString,
                )


class ChampionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetChampionByName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChampionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetChampionByName': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChampionByName,
                    request_deserializer=champion__pb2.ChampionNameRequest.FromString,
                    response_serializer=champion__pb2.Champion.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ChampionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ChampionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetChampionByName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ChampionService/GetChampionByName',
            champion__pb2.ChampionNameRequest.SerializeToString,
            champion__pb2.Champion.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
