# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: champion.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63hampion.proto\"K\n\x08\x43hampion\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06\x63lasse\x18\x02 \x01(\t\x12\x0e\n\x06origin\x18\x03 \x01(\t\x12\x11\n\tabilities\x18\x04 \x03(\t\"#\n\x13\x43hampionNameRequest\x12\x0c\n\x04name\x18\x01 \x01(\t2G\n\x0f\x43hampionService\x12\x34\n\x11GetChampionByName\x12\x14.ChampionNameRequest\x1a\t.Championb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'champion_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_CHAMPION']._serialized_start=18
  _globals['_CHAMPION']._serialized_end=93
  _globals['_CHAMPIONNAMEREQUEST']._serialized_start=95
  _globals['_CHAMPIONNAMEREQUEST']._serialized_end=130
  _globals['_CHAMPIONSERVICE']._serialized_start=132
  _globals['_CHAMPIONSERVICE']._serialized_end=203
# @@protoc_insertion_point(module_scope)
