# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import lol_champions_pb2 as lol__champions__pb2


class ChampionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetChampionInfo = channel.unary_unary(
                '/lol.ChampionService/GetChampionInfo',
                request_serializer=lol__champions__pb2.ChampionRequest.SerializeToString,
                response_deserializer=lol__champions__pb2.ChampionResponse.FromString,
                )


class ChampionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetChampionInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChampionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetChampionInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChampionInfo,
                    request_deserializer=lol__champions__pb2.ChampionRequest.FromString,
                    response_serializer=lol__champions__pb2.ChampionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lol.ChampionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ChampionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetChampionInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/lol.ChampionService/GetChampionInfo',
            lol__champions__pb2.ChampionRequest.SerializeToString,
            lol__champions__pb2.ChampionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
