# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lol_champions.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13lol_champions.proto\x12\x03lol\"\x1f\n\x0f\x43hampionRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"U\n\x10\x43hampionResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04role\x18\x02 \x01(\t\x12\x12\n\ndifficulty\x18\x03 \x01(\x05\x12\x11\n\tabilities\x18\x04 \x03(\t2S\n\x0f\x43hampionService\x12@\n\x0fGetChampionInfo\x12\x14.lol.ChampionRequest\x1a\x15.lol.ChampionResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lol_champions_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_CHAMPIONREQUEST']._serialized_start=28
  _globals['_CHAMPIONREQUEST']._serialized_end=59
  _globals['_CHAMPIONRESPONSE']._serialized_start=61
  _globals['_CHAMPIONRESPONSE']._serialized_end=146
  _globals['_CHAMPIONSERVICE']._serialized_start=148
  _globals['_CHAMPIONSERVICE']._serialized_end=231
# @@protoc_insertion_point(module_scope)
